version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  chat-score:
    image: chat-score
    build:
      context: ../../
      dockerfile: docker/chat-score/Dockerfile
      args:
        - PAT=${PAT}
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SCORING_KEY=secret
      - SECRET_KEY=secret
