apiVersion: v1
kind: Service
metadata:
  name: challenge-home-service
spec:
  selector:
    app: challenge-home
  ports:
    - name: web-port
      protocol: TCP
      port: 5000
      targetPort: http-web-svc