apiVersion: v1
kind: Service
metadata:
  name: chat-scoring-service
spec:
  selector:
    app: chat-scoring
  ports:
    - name: web-port
      protocol: TCP
      port: 5000
      targetPort: http-web-svc
