apiVersion: v1
kind: Service
metadata:
  name: picture-submission-service
spec:
  selector:
    app: picture-submission
  ports:
    - name: web-port
      protocol: TCP
      port: 5000
      targetPort: http-web-svc
