apiVersion: v1
kind: Service
metadata:
  name: rce-challenge-service
spec:
  ports:
  - port: 8000
    name: http
    protocol: TCP
    targetPort: 8000

  - port: 8080
    name: http-mgmt
    protocol: TCP
    targetPort: 8080
  
  - port: 8081
    name: http-mgmt2
    protocol: TCP
    targetPort: 8081
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: rce-challenge-service-1
  labels:
    kubernetes.io/service-name: rce-challenge-service
addressType: IPv4
ports:
  - name: http
    appProtocol: HTTP
    protocol: TCP
    port: 8000

  - name: http-mgmt
    appProtocol: HTTP
    protocol: TCP
    port: 8080

  - name: http-mgmt2
    appProtocol: HTTP
    protocol: TCP
    port: 8081
endpoints:
  - addresses:
      - "10.18.0.4"